package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Advise generated by hbm2java
 */
@Entity
@Table(name="tb_c_advise")
public class Advise  implements java.io.Serializable {


	 private static final long serialVersionUID = 3592837393904213874L;
	 private String adviseId;
     private String companyId;
     private String content;
     private String adviseMan;
     private Date adviseDate;
     private String remark;

    public Advise() {
    }

	
    public Advise(String adviseId) {
        this.adviseId = adviseId;
    }
    public Advise(String adviseId, String companyId, String content, String adviseMan, Date adviseDate, String remark) {
       this.adviseId = adviseId;
       this.companyId = companyId;
       this.content = content;
       this.adviseMan = adviseMan;
       this.adviseDate = adviseDate;
       this.remark = remark;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="advise_id", unique=true, nullable=false, length=32)
    public String getAdviseId() {
        return this.adviseId;
    }
    
    public void setAdviseId(String adviseId) {
        this.adviseId = adviseId;
    }
    
    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="content", length=2000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    @Column(name="advise_man", length=32)
    public String getAdviseMan() {
        return this.adviseMan;
    }
    
    public void setAdviseMan(String adviseMan) {
        this.adviseMan = adviseMan;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="advise_date", length=19)
    public Date getAdviseDate() {
        return this.adviseDate;
    }
    
    public void setAdviseDate(Date adviseDate) {
        this.adviseDate = adviseDate;
    }
    
    @Column(name="remark", length=32)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


