package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Areas generated by hbm2java
 */
@Entity
@Table(name="areas")
public class Areas  implements java.io.Serializable {


	 private static final long serialVersionUID = 8751641462491939535L;
	 private int id;
     private String areaid;
     private String area;
     private String cityid;

    public Areas() {
    }

	
    public Areas(int id, String areaid, String area) {
        this.id = id;
        this.areaid = areaid;
        this.area = area;
    }
    public Areas(int id, String areaid, String area, String cityid) {
       this.id = id;
       this.areaid = areaid;
       this.area = area;
       this.cityid = cityid;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="areaid", nullable=false, length=20)
    public String getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }
    
    @Column(name="area", nullable=false, length=50)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    
    @Column(name="cityid", length=20)
    public String getCityid() {
        return this.cityid;
    }
    
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }




}


