package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name="cities")
public class Cities  implements java.io.Serializable {


	 private static final long serialVersionUID = -5491477788585161351L;
	 private int id;
     private String cityid;
     private String city;
     private String provinceid;

    public Cities() {
    }

    public Cities(int id, String cityid, String city, String provinceid) {
       this.id = id;
       this.cityid = cityid;
       this.city = city;
       this.provinceid = provinceid;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="cityid", nullable=false, length=20)
    public String getCityid() {
        return this.cityid;
    }
    
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }
    
    @Column(name="city", nullable=false, length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="provinceid", nullable=false, length=20)
    public String getProvinceid() {
        return this.provinceid;
    }
    
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }




}


