package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-27 10:57:55 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CompanyChanged generated by hbm2java
 */
@Entity
@Table(name="tb_c_company_changed")
public class CompanyChanged  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = 1942123188290639450L;
	 private CompanyChangedId id;
     private String updateType;
     private String mark1;
     private String mark2;

    public CompanyChanged() {
    }

	
    public CompanyChanged(CompanyChangedId id) {
        this.id = id;
    }
    public CompanyChanged(CompanyChangedId id, String updateType, String mark1, String mark2) {
       this.id = id;
       this.updateType = updateType;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="companyId", column=@Column(name="company_id", nullable=false, length=32) ), 
        @AttributeOverride(name="companyVersion", column=@Column(name="company_version", nullable=false) ) } )
    public CompanyChangedId getId() {
        return this.id;
    }
    
    public void setId(CompanyChangedId id) {
        this.id = id;
    }
    
    @Column(name="update_type", length=2)
    public String getUpdateType() {
        return this.updateType;
    }
    
    public void setUpdateType(String updateType) {
        this.updateType = updateType;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


