package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-27 10:57:55 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompanyChangedId generated by hbm2java
 */
@Embeddable
public class CompanyChangedId  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = 1533781362378457630L;
	 private String companyId;
     private int companyVersion;

    public CompanyChangedId() {
    }

    public CompanyChangedId(String companyId, int companyVersion) {
       this.companyId = companyId;
       this.companyVersion = companyVersion;
    }
   

    @Column(name="company_id", nullable=false, length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    @Column(name="company_version", nullable=false)
    public int getCompanyVersion() {
        return this.companyVersion;
    }
    
    public void setCompanyVersion(int companyVersion) {
        this.companyVersion = companyVersion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompanyChangedId) ) return false;
		 CompanyChangedId castOther = ( CompanyChangedId ) other; 
         
		 return ( (this.getCompanyId()==castOther.getCompanyId()) || ( this.getCompanyId()!=null && castOther.getCompanyId()!=null && this.getCompanyId().equals(castOther.getCompanyId()) ) )
 && (this.getCompanyVersion()==castOther.getCompanyVersion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCompanyId() == null ? 0 : this.getCompanyId().hashCode() );
         result = 37 * result + this.getCompanyVersion();
         return result;
   }   


}


