package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-9-16 19:34:03 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * CompanyPlug generated by hbm2java
 */
@Entity
@Table(name="tb_b_company_plug")
public class CompanyPlug  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String companyPlugId;
     private String companyId;
     private String plugId;
     private Integer displayOrder;
     private String mark1;
     private String mark2;

    public CompanyPlug() {
    }

	
    public CompanyPlug(String companyPlugId) {
        this.companyPlugId = companyPlugId;
    }
    public CompanyPlug(String companyPlugId, String companyId, String plugId, Integer displayOrder, String mark1, String mark2) {
       this.companyPlugId = companyPlugId;
       this.companyId = companyId;
       this.plugId = plugId;
       this.displayOrder = displayOrder;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
   	@Id
   	@GeneratedValue(generator = "generator")
    @Column(name="company_plug_id", unique=true, nullable=false, length=32)
    public String getCompanyPlugId() {
        return this.companyPlugId;
    }
    
    public void setCompanyPlugId(String companyPlugId) {
        this.companyPlugId = companyPlugId;
    }
    
    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="plug_id", length=32)
    public String getPlugId() {
        return this.plugId;
    }
    
    public void setPlugId(String plugId) {
        this.plugId = plugId;
    }
    
    @Column(name="display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


