package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ConfigType generated by hbm2java
 */
@Entity
@Table(name="tb_c_config_type")
public class ConfigType  implements java.io.Serializable {


	 private static final long serialVersionUID = 3801670226056404124L;
	 private String typeId;
     private String typeName;
     private String typeCode;
     private String processClass;
     private String description;
     private String status;
     private Integer displayOrder;
     private Set<MetaData> metaDatas = new HashSet<MetaData>(0);

    public ConfigType() {
    }

	
    public ConfigType(String typeId) {
        this.typeId = typeId;
    }
    public ConfigType(String typeId, String typeName, String typeCode, String processClass, String description, String status, Integer displayOrder, Set<MetaData> metaDatas) {
       this.typeId = typeId;
       this.typeName = typeName;
       this.typeCode = typeCode;
       this.processClass = processClass;
       this.description = description;
       this.status = status;
       this.displayOrder = displayOrder;
       this.metaDatas = metaDatas;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="type_id", unique=true, nullable=false, length=32)
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
    
    @Column(name="type_name", length=64)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    
    @Column(name="type_code", length=32)
    public String getTypeCode() {
        return this.typeCode;
    }
    
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }
    
    @Column(name="process_class", length=512)
    public String getProcessClass() {
        return this.processClass;
    }
    
    public void setProcessClass(String processClass) {
        this.processClass = processClass;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    public Set<MetaData> getMetaDatas() {
        return this.metaDatas;
    }
    
    public void setMetaDatas(Set<MetaData> metaDatas) {
        this.metaDatas = metaDatas;
    }




}


