package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DepartmentVersion generated by hbm2java
 */
@Entity
@Table(name="tb_c_department_version")
public class DepartmentVersion  implements java.io.Serializable {


	 private static final long serialVersionUID = -3704723881171447352L;
	 private int departmentVersionNum;
     private Date updateDate;
     private String mark1;
     private String mark2;
     private Set<DepartmentChanged> departmentChangeds = new HashSet<DepartmentChanged>(0);

    public DepartmentVersion() {
    }

	
    public DepartmentVersion(int departmentVersionNum) {
        this.departmentVersionNum = departmentVersionNum;
    }
    public DepartmentVersion(int departmentVersionNum, Date updateDate, String mark1, String mark2, Set<DepartmentChanged> departmentChangeds) {
       this.departmentVersionNum = departmentVersionNum;
       this.updateDate = updateDate;
       this.mark1 = mark1;
       this.mark2 = mark2;
       this.departmentChangeds = departmentChangeds;
    }
   
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="department_version_num", unique=true, nullable=false)
    public int getDepartmentVersionNum() {
        return this.departmentVersionNum;
    }
    
    public void setDepartmentVersionNum(int departmentVersionNum) {
        this.departmentVersionNum = departmentVersionNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    public Set<DepartmentChanged> getDepartmentChangeds() {
        return this.departmentChangeds;
    }
    
    public void setDepartmentChangeds(Set<DepartmentChanged> departmentChangeds) {
        this.departmentChangeds = departmentChangeds;
    }




}


