package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * DictType generated by hbm2java
 */
@Entity
@Table(name="tb_c_dict_type")
public class DictType  implements java.io.Serializable {


	 private static final long serialVersionUID = -2128386951997326014L;
	 private String typeId;
     private String companyId;
     private String typeName;
     private String typeCode;
     private String description;
     private String status;
     private Integer displayOrder;
     private Set<DictData> dictDatas = new HashSet<DictData>(0);

    public DictType() {
    }

	
    public DictType(String typeId) {
        this.typeId = typeId;
    }
    public DictType(String typeId, String companyId, String typeName, String typeCode, String description, String status, Integer displayOrder, Set<DictData> dictDatas) {
       this.typeId = typeId;
       this.companyId = companyId;
       this.typeName = typeName;
       this.typeCode = typeCode;
       this.description = description;
       this.status = status;
       this.displayOrder = displayOrder;
       this.dictDatas = dictDatas;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="type_id", unique=true, nullable=false, length=32)
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
    
    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="type_name", length=64)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    
    @Column(name="type_code", length=32)
    public String getTypeCode() {
        return this.typeCode;
    }
    
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }
    
    @Column(name="description", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    public Set<DictData> getDictDatas() {
        return this.dictDatas;
    }
    
    public void setDictDatas(Set<DictData> dictDatas) {
        this.dictDatas = dictDatas;
    }




}


