package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Employee generated by hbm2java.
 */
@Entity
@Table(name="tb_c_employee")
public class Employee  implements java.io.Serializable {


	 private static final long serialVersionUID = -8096888243890885122L;
	 private String employeeId;
     private String departmentId;
     private String mobileShort;
     private String telShort;
     private String telephone2;
     private String headshipId;
     private String employeeCode;
     private String employeeName;
     private String employeeFirstword;
     private String employeeFullword;
     private String departmentName;
     private String idCard;
     private String resume;
     private Integer age;
     private String sex;
     private String politicsStatus;
     private String nativePlace;
     private String school;
     private String degree;
     private Date graduationDate;
     private String mobile;
     private String backupMobile;
     private String telephone;
     private String email;
     private String qq;
     private Date birthday;
     private String picture;
     private String higherUp;
     private String isDeptLeader;
     private Date joinDate;
     private Date leaveDate;
     private String leaveReason;
     private String comment;
     private String status;
     private Integer displayOrder;
     private String gridNumber;
     private String delFlag;
     private String companyCity;
     private String mark1;
     private String mark2;
     private Set<TxluserModifyusers> txluserModifyuserses = new HashSet<TxluserModifyusers>(0);

    public Employee() {
    }

	
    public Employee(String employeeId) {
        this.employeeId = employeeId;
    }
    public Employee(String employeeId, String departmentId, String mobileShort, String telShort, 
    		String telephone2, String headshipId, String employeeCode, String employeeName, 
    		String employeeFirstword, String employeeFullword, String idCard, String resume, 
    		Integer age, String sex, String politicsStatus, String nativePlace, String school, 
    		String degree, Date graduationDate, String mobile, String backupMobile, String telephone,
    		String email, String qq, Date birthday, String picture, String higherUp, String isDeptLeader, 
    		Date joinDate, Date leaveDate, String leaveReason, String comment, String status, 
    		Integer displayOrder,String gridNumber, String delFlag, String companyCity, String mark1, String mark2, Set<TxluserModifyusers> txluserModifyuserses) {
       this.employeeId = employeeId;
       this.departmentId = departmentId;
       this.mobileShort = mobileShort;
       this.telShort = telShort;
       this.telephone2 = telephone2;
       this.headshipId = headshipId;
       this.employeeCode = employeeCode;
       this.employeeName = employeeName;
       this.employeeFirstword = employeeFirstword;
       this.employeeFullword = employeeFullword;
       this.idCard = idCard;
       this.resume = resume;
       this.age = age;
       this.sex = sex;
       this.politicsStatus = politicsStatus;
       this.nativePlace = nativePlace;
       this.school = school;
       this.degree = degree;
       this.graduationDate = graduationDate;
       this.mobile = mobile;
       this.backupMobile = backupMobile;
       this.telephone = telephone;
       this.email = email;
       this.qq = qq;
       this.birthday = birthday;
       this.picture = picture;
       this.higherUp = higherUp;
       this.isDeptLeader = isDeptLeader;
       this.joinDate = joinDate;
       this.leaveDate = leaveDate;
       this.leaveReason = leaveReason;
       this.comment = comment;
       this.status = status;
       this.displayOrder = displayOrder;
       this.gridNumber = gridNumber;
       this.delFlag = delFlag;
       this.companyCity = companyCity;
       this.mark1 = mark1;
       this.mark2 = mark2;
       this.txluserModifyuserses = txluserModifyuserses;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="employee_id", unique=true, nullable=false, length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name = "department_id", length = 32)
	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}
    
    @Column(name="mobile_short", length=20)
    public String getMobileShort() {
        return this.mobileShort;
    }
    
    public void setMobileShort(String mobileShort) {
        this.mobileShort = mobileShort;
    }
    
    @Column(name="tel_short", length=20)
    public String getTelShort() {
        return this.telShort;
    }
    
    public void setTelShort(String telShort) {
        this.telShort = telShort;
    }
    
    @Column(name="telephone2", length=20)
    public String getTelephone2() {
        return this.telephone2;
    }
    
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }
    
    @Column(name="headship_id", length=32)
    public String getHeadshipId() {
        return this.headshipId;
    }
    
    public void setHeadshipId(String headshipId) {
        this.headshipId = headshipId;
    }
    
    @Column(name="employee_code", length=32)
    public String getEmployeeCode() {
        return this.employeeCode;
    }
    
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }
    
    @Column(name="employee_name", length=64)
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
    
    @Column(name="employee_firstword", length=64)
    public String getEmployeeFirstword() {
		return employeeFirstword;
	}


	public void setEmployeeFirstword(String employeeFirstword) {
		this.employeeFirstword = employeeFirstword;
	}

	@Column(name="employee_fullword", length=256)
	public String getEmployeeFullword() {
		return employeeFullword;
	}


	public void setEmployeeFullword(String employeeFullword) {
		this.employeeFullword = employeeFullword;
	}

	@Column(name="parent_department_name", length=256)
	public String getDepartmentName() {
		return departmentName;
	}


	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}


	@Column(name="id_card", length=18)
    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }
    
    @Column(name="resume")
    public String getResume() {
        return this.resume;
    }
    
    public void setResume(String resume) {
        this.resume = resume;
    }
    
    @Column(name="age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    
    @Column(name="sex", length=1)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="politics_status", length=2)
    public String getPoliticsStatus() {
        return this.politicsStatus;
    }
    
    public void setPoliticsStatus(String politicsStatus) {
        this.politicsStatus = politicsStatus;
    }
    
    @Column(name="native_place", length=64)
    public String getNativePlace() {
        return this.nativePlace;
    }
    
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }
    
    @Column(name="school", length=64)
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    
    @Column(name="degree", length=2)
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="graduation_date", length=19)
    public Date getGraduationDate() {
        return this.graduationDate;
    }
    
    public void setGraduationDate(Date graduationDate) {
        this.graduationDate = graduationDate;
    }
    
    @Column(name="mobile", length=12)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="backup_mobile", length=12)
    public String getBackupMobile() {
        return this.backupMobile;
    }
    
    public void setBackupMobile(String backupMobile) {
        this.backupMobile = backupMobile;
    }
    
    @Column(name="telephone", length=15)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    @Column(name="email", length=32)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="qq", length=18)
    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="birthday", length=19)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    
    @Column(name="picture", length=256)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    
    @Column(name="higher_up", length=32)
    public String getHigherUp() {
        return this.higherUp;
    }
    
    public void setHigherUp(String higherUp) {
        this.higherUp = higherUp;
    }
    
    @Column(name="is_dept_leader", length=2)
    public String getIsDeptLeader() {
        return this.isDeptLeader;
    }
    
    public void setIsDeptLeader(String isDeptLeader) {
        this.isDeptLeader = isDeptLeader;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="join_date", length=19)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="leave_date", length=19)
    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }
    
    @Column(name="leave_reason", length=1024)
    public String getLeaveReason() {
        return this.leaveReason;
    }
    
    public void setLeaveReason(String leaveReason) {
        this.leaveReason = leaveReason;
    }
    
    @Column(name="comment", length=1024)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    @Column(name="status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="display_order", length=8)
    public Integer getDisplayOrder() {
		return displayOrder;
	}


	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name="grid_number", length=32)
	public String getGridNumber() {
		return gridNumber;
	}


	public void setGridNumber(String gridNumber) {
		this.gridNumber = gridNumber;
	}


	@Column(name="del_flag", length=1)
    public String getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
    
    @Column(name="company_city", length=1)
    public String getCompanyCity() {
        return this.companyCity;
    }
    
    public void setcompanyCity(String companyCity) {
        this.companyCity = companyCity;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    public Set<TxluserModifyusers> getTxluserModifyuserses() {
        return this.txluserModifyuserses;
    }
    
    public void setTxluserModifyuserses(Set<TxluserModifyusers> txluserModifyuserses) {
        this.txluserModifyuserses = txluserModifyuserses;
    }




}


