package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-6-8 15:09:26 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * EmployeeReport generated by hbm2java
 */
@Entity
@Table(name="tb_c_employee_report")
public class EmployeeReport  implements java.io.Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = 1L;
	 private String employeeReportId;
	 private String employeeId;
	 private String movementId;
     private Integer allSportTimes;
     private BigInteger allSportElpseTime;
     private Integer allSportSteps;
     private BigDecimal allSportDistence;
     private BigDecimal avgSportSpeed;
     private Integer avgSportSteps;
     private BigInteger avgSportTime;
     private Integer currentRank;
     private Integer sportLevel;
     private Date sportFirstDate;
     private Date sportNearestTime;
     private Integer singleMaxSteps;
     private long singleMaxTime;
     private BigDecimal singleMaxSpeed;
     private Integer gpsTimes;
     private BigDecimal allGpsDistence;
     private Integer allGpsSteps;
     private BigDecimal steps;
     private Integer medalNumbers;
     private String mark1;
     private String mark2;

    public EmployeeReport() {
    }

	
    public EmployeeReport(String employeeId) {
        this.employeeId = employeeId;
    }
    public EmployeeReport(String employeeReportId, String movementId, String employeeId, Integer allSportTimes, BigInteger allSportElpseTime, Integer allSportSteps, BigDecimal allSportDistence, BigDecimal avgSportSpeed, Integer avgSportSteps, BigInteger avgSportTime, Integer currentRank, Integer sportLevel, Date sportFirstDate, Date sportNearestTime, Integer singleMaxSteps, long singleMaxTime, Integer gpsTimes, BigDecimal allGpsDistence, Integer allGpsSteps, BigDecimal steps, Integer medalNumbers, String mark1, String mark2) {
       this.employeeReportId = employeeReportId;
       this.movementId = movementId;
       this.employeeId = employeeId;
       this.allSportTimes = allSportTimes;
       this.allSportElpseTime = allSportElpseTime;
       this.allSportSteps = allSportSteps;
       this.allSportDistence = allSportDistence;
       this.avgSportSpeed = avgSportSpeed;
       this.avgSportSteps = avgSportSteps;
       this.avgSportTime = avgSportTime;
       this.currentRank = currentRank;
       this.sportLevel = sportLevel;
       this.sportFirstDate = sportFirstDate;
       this.sportNearestTime = sportNearestTime;
       this.singleMaxSteps = singleMaxSteps;
       this.singleMaxTime = singleMaxTime;
       this.gpsTimes = gpsTimes;
       this.allGpsDistence = allGpsDistence;
       this.allGpsSteps = allGpsSteps;
       this.steps = steps;
       this.medalNumbers = medalNumbers;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   

	/**
	 * @return the employeeReportId
	 */
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="employee_report_id", unique=true, nullable=false, length=32)
	public String getEmployeeReportId() {
		return employeeReportId;
	}


	/**
	 * @param employeeReportId the employeeReportId to set
	 */
	public void setEmployeeReportId(String employeeReportId) {
		this.employeeReportId = employeeReportId;
	}


	/**
	 * @return the movementId
	 */
	@Column(name="movement_id", length=32)
	public String getMovementId() {
		return movementId;
	}


	/**
	 * @param movementId the movementId to set
	 */
	public void setMovementId(String movementId) {
		this.movementId = movementId;
	}
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="all_sport_times")
    public Integer getAllSportTimes() {
        return this.allSportTimes;
    }
    
    public void setAllSportTimes(Integer allSportTimes) {
        this.allSportTimes = allSportTimes;
    }

    @Column(name="all_sport_elpse_time")
    public BigInteger getAllSportElpseTime() {
        return this.allSportElpseTime;
    }
    
    public void setAllSportElpseTime(BigInteger allSportElpseTime) {
        this.allSportElpseTime = allSportElpseTime;
    }
    
    @Column(name="all_sport_steps")
    public Integer getAllSportSteps() {
        return this.allSportSteps;
    }
    
    public void setAllSportSteps(Integer allSportSteps) {
        this.allSportSteps = allSportSteps;
    }
    
    @Column(name="all_sport_distence", precision=10)
    public BigDecimal getAllSportDistence() {
        return this.allSportDistence;
    }
    
    public void setAllSportDistence(BigDecimal allSportDistence) {
        this.allSportDistence = allSportDistence;
    }
    
    @Column(name="avg_sport_speed", precision=10)
    public BigDecimal getAvgSportSpeed() {
        return this.avgSportSpeed;
    }
    
    public void setAvgSportSpeed(BigDecimal avgSportSpeed) {
        this.avgSportSpeed = avgSportSpeed;
    }
    
    @Column(name="avg_sport_steps")
    public Integer getAvgSportSteps() {
        return this.avgSportSteps;
    }
    
    public void setAvgSportSteps(Integer avgSportSteps) {
        this.avgSportSteps = avgSportSteps;
    }

    @Column(name="avg_sport_time")
    public BigInteger getAvgSportTime() {
        return this.avgSportTime;
    }
    
    public void setAvgSportTime(BigInteger avgSportTime) {
        this.avgSportTime = avgSportTime;
    }
    
    @Column(name="current_rank")
    public Integer getCurrentRank() {
        return this.currentRank;
    }
    
    public void setCurrentRank(Integer currentRank) {
        this.currentRank = currentRank;
    }
    
    @Column(name="sport_level")
    public Integer getSportLevel() {
        return this.sportLevel;
    }
    
    public void setSportLevel(Integer sportLevel) {
        this.sportLevel = sportLevel;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sport_first_date", length=19)
    public Date getSportFirstDate() {
        return this.sportFirstDate;
    }
    
    public void setSportFirstDate(Date sportFirstDate) {
        this.sportFirstDate = sportFirstDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sport_nearest_time", length=19)
    public Date getSportNearestTime() {
        return this.sportNearestTime;
    }
    
    public void setSportNearestTime(Date sportNearestTime) {
        this.sportNearestTime = sportNearestTime;
    }
    
    @Column(name="single_max_steps")
    public Integer getSingleMaxSteps() {
        return this.singleMaxSteps;
    }
    
    public void setSingleMaxSteps(Integer singleMaxSteps) {
        this.singleMaxSteps = singleMaxSteps;
    }
    
    @Column(name="single_max_time")
    public long getSingleMaxTime() {
        return this.singleMaxTime;
    }
    
    public void setSingleMaxTime(long singleMaxTime) {
        this.singleMaxTime = singleMaxTime;
    }
    
    @Column(name="gps_times")
    public Integer getGpsTimes() {
        return this.gpsTimes;
    }
    
    public void setGpsTimes(Integer gpsTimes) {
        this.gpsTimes = gpsTimes;
    }
    
    @Column(name="all_gps_distence", precision=10)
    public BigDecimal getAllGpsDistence() {
        return this.allGpsDistence;
    }
    
    public void setAllGpsDistence(BigDecimal allGpsDistence) {
        this.allGpsDistence = allGpsDistence;
    }
    
    @Column(name="all_gps_steps")
    public Integer getAllGpsSteps() {
        return this.allGpsSteps;
    }
    
    public void setAllGpsSteps(Integer allGpsSteps) {
        this.allGpsSteps = allGpsSteps;
    }
    
    @Column(name="steps", precision=10)
    public BigDecimal getSteps() {
        return this.steps;
    }
    
    public void setSteps(BigDecimal steps) {
        this.steps = steps;
    }
    
    @Column(name="medal_numbers")
    public Integer getMedalNumbers() {
        return this.medalNumbers;
    }
    
    public void setMedalNumbers(Integer medalNumbers) {
        this.medalNumbers = medalNumbers;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }


    @Column(name="single_max_speed", precision=10)
	public BigDecimal getSingleMaxSpeed() {
		return singleMaxSpeed;
	}


	public void setSingleMaxSpeed(BigDecimal singleMaxSpeed) {
		this.singleMaxSpeed = singleMaxSpeed;
	}




}


