package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-6-8 15:09:26 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * EmployeeRecord generated by hbm2java
 */
@Entity
@Table(name="tb_c_employee_record")
public class EmployeeRecord  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String employeeRecordId;
     private String employeeId;
     private String movementId;
     private String employeeRecordModel;
     private Date updateDate;
     private Date sportDate;
     private Date sportStartTime;
     private Date sportEndTime;
     private long sportElapseTime;
     private Integer sportStep;
     private BigDecimal sportDistence;
     private BigDecimal sportSpeed;
     private BigDecimal sportCalories;
     private String gpsStatus;
     private BigDecimal gpsDistence;
     private Integer gpsSteps;
     private Integer modeChangeTimes;
     private BigDecimal stepCalc;
     private BigDecimal stepError;
     private String mark1;
     private String mark2;

    public EmployeeRecord() {
    }

	
    public EmployeeRecord(String employeeRecordId) {
        this.employeeRecordId = employeeRecordId;
    }
    public EmployeeRecord(String employeeRecordId, String employeeId, String movementId, String employeeRecordModel, Date updateDate, Date sportDate, Date sportStartTime, Date sportEndTime, long sportElapseTime, Integer sportStep, BigDecimal sportDistence, BigDecimal sportSpeed, BigDecimal sportCalories, String gpsStatus, BigDecimal gpsDistence, Integer gpsSteps, Integer modeChangeTimes, BigDecimal stepCalc, BigDecimal stepError, String mark1, String mark2) {
       this.employeeRecordId = employeeRecordId;
       this.employeeId = employeeId;
       this.movementId = movementId;
       this.employeeRecordModel = employeeRecordModel;
       this.updateDate = updateDate;
       this.sportDate = sportDate;
       this.sportStartTime = sportStartTime;
       this.sportEndTime = sportEndTime;
       this.sportElapseTime = sportElapseTime;
       this.sportStep = sportStep;
       this.sportDistence = sportDistence;
       this.sportSpeed = sportSpeed;
       this.sportCalories = sportCalories;
       this.gpsStatus = gpsStatus;
       this.gpsDistence = gpsDistence;
       this.gpsSteps = gpsSteps;
       this.modeChangeTimes = modeChangeTimes;
       this.stepCalc = stepCalc;
       this.stepError = stepError;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="employee_record_id", unique=true, nullable=false, length=32)
    public String getEmployeeRecordId() {
        return this.employeeRecordId;
    }
    
    public void setEmployeeRecordId(String employeeRecordId) {
        this.employeeRecordId = employeeRecordId;
    }
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="employee_record_model", length=2)
    public String getEmployeeRecordModel() {
        return this.employeeRecordModel;
    }
    
    public void setEmployeeRecordModel(String employeeRecordModel) {
        this.employeeRecordModel = employeeRecordModel;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="sport_date", length=10)
    public Date getSportDate() {
        return this.sportDate;
    }
    
    public void setSportDate(Date sportDate) {
        this.sportDate = sportDate;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="sport_start_time", length=8)
    public Date getSportStartTime() {
        return this.sportStartTime;
    }
    
    public void setSportStartTime(Date sportStartTime) {
        this.sportStartTime = sportStartTime;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="sport_end_time", length=8)
    public Date getSportEndTime() {
        return this.sportEndTime;
    }
    
    public void setSportEndTime(Date sportEndTime) {
        this.sportEndTime = sportEndTime;
    }
    
    @Column(name="sport_elapse_time")
    public long getSportElapseTime() {
        return this.sportElapseTime;
    }
    
    public void setSportElapseTime(long sportElapseTime) {
        this.sportElapseTime = sportElapseTime;
    }
    
    @Column(name="sport_step")
    public Integer getSportStep() {
        return this.sportStep;
    }
    
    public void setSportStep(Integer sportStep) {
        this.sportStep = sportStep;
    }
    
    @Column(name="sport_distence", precision=10)
    public BigDecimal getSportDistence() {
        return this.sportDistence;
    }
    
    public void setSportDistence(BigDecimal sportDistence) {
        this.sportDistence = sportDistence;
    }
    
    @Column(name="sport_speed", precision=10)
    public BigDecimal getSportSpeed() {
        return this.sportSpeed;
    }
    
    public void setSportSpeed(BigDecimal sportSpeed) {
        this.sportSpeed = sportSpeed;
    }
    
    @Column(name="sport_calories", precision=10)
    public BigDecimal getSportCalories() {
        return this.sportCalories;
    }
    
    public void setSportCalories(BigDecimal sportCalories) {
        this.sportCalories = sportCalories;
    }
    
    @Column(name="gps_status", length=2)
    public String getGpsStatus() {
        return this.gpsStatus;
    }
    
    public void setGpsStatus(String gpsStatus) {
        this.gpsStatus = gpsStatus;
    }
    
    @Column(name="gps_distence", precision=10)
    public BigDecimal getGpsDistence() {
        return this.gpsDistence;
    }
        
    public void setGpsDistence(BigDecimal gpsDistence) {
        this.gpsDistence = gpsDistence;
    }
    
    @Column(name="gps_steps",precision=10)
    public Integer getGpsSteps()
    {
    	return this.gpsSteps;
    }
    
    public void setGpsSteps(Integer gpsSteps)
    {
    	this.gpsSteps = gpsSteps;
    }
    
    @Column(name="mode_change_times")
    public Integer getModeChangeTimes() {
        return this.modeChangeTimes;
    }
    
    public void setModeChangeTimes(Integer modeChangeTimes) {
        this.modeChangeTimes = modeChangeTimes;
    }
    
    @Column(name="step_calc", precision=10)
    public BigDecimal getStepCalc() {
        return this.stepCalc;
    }
    
    public void setStepCalc(BigDecimal stepCalc) {
        this.stepCalc = stepCalc;
    }
    
    @Column(name="step_error", precision=10)
    public BigDecimal getStepError() {
        return this.stepError;
    }
    
    public void setStepError(BigDecimal stepError) {
        this.stepError = stepError;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }


	/**
	 * @return 活动编号
	 */
    @Column(name="movement_id", length=32)
	public String getMovementId() {
		return movementId;
	}


	/**
	 * @param movementId the movementId to set
	 */
	public void setMovementId(String movementId) {
		this.movementId = movementId;
	}




}


