package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-6-8 14:55:32 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeParam generated by hbm2java
 */
@Entity
@Table(name="tb_c_employee_param")
public class EmployeeParam  implements java.io.Serializable {


     private String employeeId;
     private BigDecimal employeeHeight;
     private BigDecimal employeeWeight;
     private BigDecimal employyeeStep;
     private String mark1;
     private String mark2;

    public EmployeeParam() {
    }

	
    public EmployeeParam(String employeeId) {
        this.employeeId = employeeId;
    }
    public EmployeeParam(String employeeId, BigDecimal employeeHeight, BigDecimal employeeWeight, BigDecimal employyeeStep, String mark1, String mark2) {
       this.employeeId = employeeId;
       this.employeeHeight = employeeHeight;
       this.employeeWeight = employeeWeight;
       this.employyeeStep = employyeeStep;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @Id 
    @Column(name="employee_id", unique=true, nullable=false, length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="employee_height", precision=10, scale=1)
    public BigDecimal getEmployeeHeight() {
        return this.employeeHeight;
    }
    
    public void setEmployeeHeight(BigDecimal employeeHeight) {
        this.employeeHeight = employeeHeight;
    }
    
    @Column(name="employee_weight", precision=10, scale=1)
    public BigDecimal getEmployeeWeight() {
        return this.employeeWeight;
    }
    
    public void setEmployeeWeight(BigDecimal employeeWeight) {
        this.employeeWeight = employeeWeight;
    }
    
    @Column(name="employyee_step", precision=10, scale=1)
    public BigDecimal getEmployyeeStep() {
        return this.employyeeStep;
    }
    
    public void setEmployyeeStep(BigDecimal employyeeStep) {
        this.employyeeStep = employyeeStep;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


