package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-8-16 19:28:35 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Focus generated by hbm2java
 */
@Entity
@Table(name="tb_b_focus")
public class Focus  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String focusId;
     private String employeeId;
     private String foucsEmployeeId;
     private String mark1;
     private String mark2;

    public Focus() {
    }

	
    public Focus(String focusId) {
        this.focusId = focusId;
    }
    public Focus(String focusId, String employeeId, String foucsEmployeeId, String mark1, String mark2) {
       this.focusId = focusId;
       this.employeeId = employeeId;
       this.foucsEmployeeId = foucsEmployeeId;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
     @Id 
    
    @Column(name="focus_id", unique=true, nullable=false, length=32)
    public String getFocusId() {
        return this.focusId;
    }
    
    public void setFocusId(String focusId) {
        this.focusId = focusId;
    }
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="foucs_employee_id", length=32)
    public String getFoucsEmployeeId() {
        return this.foucsEmployeeId;
    }
    
    public void setFoucsEmployeeId(String foucsEmployeeId) {
        this.foucsEmployeeId = foucsEmployeeId;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


