package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-24 16:40:53 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupVersion generated by hbm2java
 */
@Entity
@Table(name="tb_c_group_version")
public class GroupVersion  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = -7711780285017971420L;
	 private Integer groupVersionNum;
     private Date updateDate;
     private String mark1;
     private String mark2;

    public GroupVersion() {
    }

    public GroupVersion(Date updateDate, String mark1, String mark2) {
       this.updateDate = updateDate;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="group_version_num", unique=true, nullable=false)
    public Integer getGroupVersionNum() {
        return this.groupVersionNum;
    }
    
    public void setGroupVersionNum(Integer groupVersionNum) {
        this.groupVersionNum = groupVersionNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


