package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-22 21:25:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * GroupUsers generated by hbm2java
 */
@Entity
@Table(name="tb_b_group_users")
public class GroupUsers  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = 2222628917231361715L;
	 private String groupEmployeeId;
     private Group group;
     private String employeeId;
     private String mark1;
     private String mark2;

    public GroupUsers() {
    }

	
    public GroupUsers(String groupEmployeeId) {
        this.groupEmployeeId = groupEmployeeId;
    }
    public GroupUsers(String groupEmployeeId, Group group, String employeeId, String mark1, String mark2) {
       this.groupEmployeeId = groupEmployeeId;
       this.group = group;
       this.employeeId = employeeId;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="group_employee_id", unique=true, nullable=false, length=32)
    public String getGroupEmployeeId() {
        return this.groupEmployeeId;
    }
    
    public void setGroupEmployeeId(String groupEmployeeId) {
        this.groupEmployeeId = groupEmployeeId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id")
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


