package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-7-19 15:21:50 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Holidayskin generated by hbm2java
 */

@Entity
@Table(name="tb_c_holidayskin")
public class Holidayskin  implements java.io.Serializable {

	private static final long serialVersionUID = 2699971523403987631L;
	private String holidayskinId;
     private String holidayskinName;
     private String holidayName;
     private Date holidayskinStartDate;
     private Date holidayskinEndDate;
     private String holidayskinPath;
     private String holidayskinStatus;
     private String holidayskinRepeat;
     private String mark1;
     private String mark2;

    public Holidayskin() {
    }

	
    public Holidayskin(String holidayskinId) {
        this.holidayskinId = holidayskinId;
    }
    public Holidayskin(String holidayskinId, String holidayskinName, String holidayName, Date holidayskinStartDate, Date holidayskinEndDate, String holidayskinPath, String holidayskinStatus, String holidayskinRepeat, String mark1, String mark2) {
       this.holidayskinId = holidayskinId;
       this.holidayskinName = holidayskinName;
       this.holidayName = holidayName;
       this.holidayskinStartDate = holidayskinStartDate;
       this.holidayskinEndDate = holidayskinEndDate;
       this.holidayskinPath = holidayskinPath;
       this.holidayskinStatus = holidayskinStatus;
       this.holidayskinRepeat = holidayskinRepeat;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="holidayskin_id", unique=true, nullable=false, length=32)
    public String getHolidayskinId() {
        return this.holidayskinId;
    }
    
    public void setHolidayskinId(String holidayskinId) {
        this.holidayskinId = holidayskinId;
    }
    
    @Column(name="holidayskin_name", length=80)
    public String getHolidayskinName() {
        return this.holidayskinName;
    }
    
    public void setHolidayskinName(String holidayskinName) {
        this.holidayskinName = holidayskinName;
    }
    
    @Column(name="holiday_name", length=80)
    public String getHolidayName() {
        return this.holidayName;
    }
    
    public void setHolidayName(String holidayName) {
        this.holidayName = holidayName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="holidayskin_start_date", length=19)
    public Date getHolidayskinStartDate() {
        return this.holidayskinStartDate;
    }
    
    public void setHolidayskinStartDate(Date holidayskinStartDate) {
        this.holidayskinStartDate = holidayskinStartDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="holidayskin_end_date", length=19)
    public Date getHolidayskinEndDate() {
        return this.holidayskinEndDate;
    }
    
    public void setHolidayskinEndDate(Date holidayskinEndDate) {
        this.holidayskinEndDate = holidayskinEndDate;
    }
    
    @Column(name="holidayskin_path", length=200)
    public String getHolidayskinPath() {
        return this.holidayskinPath;
    }
    
    public void setHolidayskinPath(String holidayskinPath) {
        this.holidayskinPath = holidayskinPath;
    }
    
    @Column(name="holidayskin_status", length=1)
    public String getHolidayskinStatus() {
        return this.holidayskinStatus;
    }
    
    public void setHolidayskinStatus(String holidayskinStatus) {
        this.holidayskinStatus = holidayskinStatus;
    }
    
    @Column(name="holidayskin_repeat", length=1)
    public String getHolidayskinRepeat() {
        return this.holidayskinRepeat;
    }
    
    public void setHolidayskinRepeat(String holidayskinRepeat) {
        this.holidayskinRepeat = holidayskinRepeat;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }
}