package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-12-24 15:05:06 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IntegrationDetail generated by hbm2java
 */
@Entity
@Table(name="tb_c_integration_detail")
public class IntegrationDetail  implements java.io.Serializable {


     private String integrationDetailId;
     private String integrationDetailYear;
     private String integrationDetailMonth;
     private Integer integrationDetailValue;
     private String employeeId;
     private String movementId;
     private String mark1;
     private String mark2;
     private String mark3;
     private String mark4;

    public IntegrationDetail() {
    }

	
    public IntegrationDetail(String integrationDetailId) {
        this.integrationDetailId = integrationDetailId;
    }
    public IntegrationDetail(String integrationDetailId, String integrationDetailYear, String integrationDetailMonth, Integer integrationDetailValue, String employeeId, String movementId, String mark1, String mark2, String mark3, String mark4) {
       this.integrationDetailId = integrationDetailId;
       this.integrationDetailYear = integrationDetailYear;
       this.integrationDetailMonth = integrationDetailMonth;
       this.integrationDetailValue = integrationDetailValue;
       this.employeeId = employeeId;
       this.movementId = movementId;
       this.mark1 = mark1;
       this.mark2 = mark2;
       this.mark3 = mark3;
       this.mark4 = mark4;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="integration_detail_id", unique=true, nullable=false, length=32)
    public String getIntegrationDetailId() {
        return this.integrationDetailId;
    }
    
    public void setIntegrationDetailId(String integrationDetailId) {
        this.integrationDetailId = integrationDetailId;
    }
    
    @Column(name="integration_detail_year", length=4)
    public String getIntegrationDetailYear() {
        return this.integrationDetailYear;
    }
    
    public void setIntegrationDetailYear(String integrationDetailYear) {
        this.integrationDetailYear = integrationDetailYear;
    }
    
    @Column(name="integration_detail_month", length=2)
    public String getIntegrationDetailMonth() {
        return this.integrationDetailMonth;
    }
    
    public void setIntegrationDetailMonth(String integrationDetailMonth) {
        this.integrationDetailMonth = integrationDetailMonth;
    }
    
    @Column(name="integration_detail_value")
    public Integer getIntegrationDetailValue() {
        return this.integrationDetailValue;
    }
    
    public void setIntegrationDetailValue(Integer integrationDetailValue) {
        this.integrationDetailValue = integrationDetailValue;
    }
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="movement_id", length=32)
    public String getMovementId() {
        return this.movementId;
    }
    
    public void setMovementId(String movementId) {
        this.movementId = movementId;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }
    
    @Column(name="mark3", length=200)
    public String getMark3() {
        return this.mark3;
    }
    
    public void setMark3(String mark3) {
        this.mark3 = mark3;
    }
    
    @Column(name="mark4", length=200)
    public String getMark4() {
        return this.mark4;
    }
    
    public void setMark4(String mark4) {
        this.mark4 = mark4;
    }




}


