package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-4-11 17:18:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterfaceLog generated by hbm2java.
 */
@Entity
@Table(name="tb_c_interface_log")
public class InterfaceLog  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>.
	 * 类型：long
	 */
	 private static final long serialVersionUID = 6549655085039142333L;
	 private long id;
     private String companyId;
     private String operateMan;
     private Date operateTime;
     private String interfaceName;

    public InterfaceLog() {
    }

	
    public InterfaceLog(long id) {
        this.id = id;
    }
    public InterfaceLog(long id, String companyId, String operateMan, Date operateTime, String interfaceName) {
       this.id = id;
       this.companyId = companyId;
       this.operateMan = operateMan;
       this.operateTime = operateTime;
       this.interfaceName = interfaceName;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="operate_man", length=32)
    public String getOperateMan() {
        return this.operateMan;
    }
    
    public void setOperateMan(String operateMan) {
        this.operateMan = operateMan;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="operate_time", length=19)
    public Date getOperateTime() {
        return this.operateTime;
    }
    
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
    
    @Column(name="interface_name", length=32)
    public String getInterfaceName() {
        return this.interfaceName;
    }
    
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }




}


