package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-12-17 18:44:35 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Integration generated by hbm2java
 */
@Entity
@Table(name="tb_c_integration")
public class Integration  implements java.io.Serializable {


     private String integrationId;
     private String employeeId;
     private Integer integrationValue;
     private Integer integrationOrder;
     private String integrationYear;
     private String mark1;
     private String mark2;
     private String mark3;
     private String mark4;

    public Integration() {
    }

	
    public Integration(String integrationId) {
        this.integrationId = integrationId;
    }
    public Integration(String integrationId, String employeeId, Integer integrationValue, Integer integrationOrder, String integrationYear, String mark1, String mark2, String mark3, String mark4) {
       this.integrationId = integrationId;
       this.employeeId = employeeId;
       this.integrationValue = integrationValue;
       this.integrationOrder = integrationOrder;
       this.integrationYear = integrationYear;
       this.mark1 = mark1;
       this.mark2 = mark2;
       this.mark3 = mark3;
       this.mark4 = mark4;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="integration_id", unique=true, nullable=false, length=32)
    public String getIntegrationId() {
        return this.integrationId;
    }
    
    public void setIntegrationId(String integrationId) {
        this.integrationId = integrationId;
    }
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="integration_value")
    public Integer getIntegrationValue() {
        return this.integrationValue;
    }
    
    public void setIntegrationValue(Integer integrationValue) {
        this.integrationValue = integrationValue;
    }
    
    @Column(name="integration_order")
    public Integer getIntegrationOrder() {
        return this.integrationOrder;
    }
    
    public void setIntegrationOrder(Integer integrationOrder) {
        this.integrationOrder = integrationOrder;
    }
    
    @Column(name="integration_year", length=4)
    public String getIntegrationYear() {
        return this.integrationYear;
    }
    
    public void setIntegrationYear(String integrationYear) {
        this.integrationYear = integrationYear;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }
    
    @Column(name="mark3", length=200)
    public String getMark3() {
        return this.mark3;
    }
    
    public void setMark3(String mark3) {
        this.mark3 = mark3;
    }
    
    @Column(name="mark4", length=200)
    public String getMark4() {
        return this.mark4;
    }
    
    public void setMark4(String mark4) {
        this.mark4 = mark4;
    }




}


