package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginOutLog generated by hbm2java
 */
@Entity
@Table(name="tb_c_login_out_log")
public class LoginOutLog  implements java.io.Serializable {


	 private static final long serialVersionUID = -2966833242864481783L;
	 private Long id;
     private String operateType;
     private Date operateTime;
     private String userId;
     private String userName;
     private String companyId;
     private String loginIp;
     private String clientType;
     private String loginResult;
     private String logContent;
     private Long timeConsuming;

    public LoginOutLog() {
    }

    public LoginOutLog(String operateType, Date operateTime, String userId, String userName, String companyId, String loginIp, String clientType, String loginResult, String logContent, Long timeConsuming) {
       this.operateType = operateType;
       this.operateTime = operateTime;
       this.userId = userId;
       this.userName = userName;
       this.companyId = companyId;
       this.loginIp = loginIp;
       this.clientType = clientType;
       this.loginResult = loginResult;
       this.logContent = logContent;
       this.timeConsuming = timeConsuming;
    }
   
    @Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="operate_type", length=1)
    public String getOperateType() {
        return this.operateType;
    }
    
    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="operate_time", length=19)
    public Date getOperateTime() {
        return this.operateTime;
    }
    
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
    
    @Column(name="user_id", length=32)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    @Column(name="user_name", length=32)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="login_ip", length=64)
    public String getLoginIp() {
        return this.loginIp;
    }
    
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }
    
    @Column(name="client_type", length=1)
    public String getClientType() {
        return this.clientType;
    }
    
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }
    
    @Column(name="login_result", length=1)
    public String getLoginResult() {
        return this.loginResult;
    }
    
    public void setLoginResult(String loginResult) {
        this.loginResult = loginResult;
    }
    
    @Column(name="log_content", length=256)
    public String getLogContent() {
        return this.logContent;
    }
    
    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }
    
    @Column(name="time_consuming")
    public Long getTimeConsuming() {
        return this.timeConsuming;
    }
    
    public void setTimeConsuming(Long timeConsuming) {
        this.timeConsuming = timeConsuming;
    }




}


