package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-10-23 15:48:18 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ManageCity generated by hbm2java
 */
@Entity
@Table(name="tb_c_manage_city")
public class ManageCity  implements java.io.Serializable {


     private String manageCityId;
     private String userId;
     private String manageCityCode;
     private String mark1;
     private String mark2;
     private String mark3;
     private String mark4;

    public ManageCity() {
    }

	
    public ManageCity(String manageCityId) {
        this.manageCityId = manageCityId;
    }
    public ManageCity(String manageCityId, String userId, String manageCityCode, String mark1, String mark2, String mark3, String mark4) {
       this.manageCityId = manageCityId;
       this.userId = userId;
       this.manageCityCode = manageCityCode;
       this.mark1 = mark1;
       this.mark2 = mark2;
       this.mark3 = mark3;
       this.mark4 = mark4;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
   	@Id
   	@GeneratedValue(generator = "generator")
    @Column(name="manage_city_id", unique=true, nullable=false, length=32)
    public String getManageCityId() {
        return this.manageCityId;
    }
    
    public void setManageCityId(String manageCityId) {
        this.manageCityId = manageCityId;
    }
    
    @Column(name="user_id", length=32)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    @Column(name="manage_city_code", length=1)
    public String getManageCityCode() {
        return this.manageCityCode;
    }
    
    public void setManageCityCode(String manageCityCode) {
        this.manageCityCode = manageCityCode;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }
    
    @Column(name="mark3", length=200)
    public String getMark3() {
        return this.mark3;
    }
    
    public void setMark3(String mark3) {
        this.mark3 = mark3;
    }
    
    @Column(name="mark4", length=200)
    public String getMark4() {
        return this.mark4;
    }
    
    public void setMark4(String mark4) {
        this.mark4 = mark4;
    }




}


