package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-22 21:25:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * MasterRules generated by hbm2java
 */
@Entity
@Table(name="tb_b_master_rules")
public class MasterRules  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = -1708230895881133308L;
	 private String rulesId;
     private Master master;
     private String rulesContent;
     private String rulesSql;
     private String mark1;
     private String mark2;

    public MasterRules() {
    }

	
    public MasterRules(String rulesId) {
        this.rulesId = rulesId;
    }
    public MasterRules(String rulesId, Master master, String rulesContent, String rulesSql, String mark1, String mark2) {
       this.rulesId = rulesId;
       this.master = master;
       this.rulesContent = rulesContent;
       this.rulesSql = rulesSql;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="rules_id", unique=true, nullable=false, length=32)
    public String getRulesId() {
        return this.rulesId;
    }
    
    public void setRulesId(String rulesId) {
        this.rulesId = rulesId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="master_id")
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    
    @Column(name="rules_content", length=4000)
    public String getRulesContent() {
        return this.rulesContent;
    }
    
    public void setRulesContent(String rulesContent) {
        this.rulesContent = rulesContent;
    }
    
    @Column(name="rules_sql", length=4000)
    public String getRulesSql() {
        return this.rulesSql;
    }
    
    public void setRulesSql(String rulesSql) {
        this.rulesSql = rulesSql;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


