package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-12-3 20:24:56 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * MedalSys generated by hbm2java
 */
@Entity
@Table(name="tb_c_medal_sys")
public class MedalSys  implements java.io.Serializable {


     private String medalSysId;
     private String medalSysName;
     private Date addDate;
     private String addMan;
     private String mark1;
     private String mark2;

    public MedalSys() {
    }

	
    public MedalSys(String medalSysId) {
        this.medalSysId = medalSysId;
    }
    public MedalSys(String medalSysId, String medalSysName, Date addDate, String addMan, String mark1, String mark2) {
       this.medalSysId = medalSysId;
       this.medalSysName = medalSysName;
       this.addDate = addDate;
       this.addMan = addMan;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   

   	@Id
    @Column(name="medal_sys_id", unique=true, nullable=false, length=32)
    public String getMedalSysId() {
        return this.medalSysId;
    }
    
    public void setMedalSysId(String medalSysId) {
        this.medalSysId = medalSysId;
    }
    
    @Column(name="medal_sys_name", length=200)
    public String getMedalSysName() {
        return this.medalSysName;
    }
    
    public void setMedalSysName(String medalSysName) {
        this.medalSysName = medalSysName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="add_date", length=19)
    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    @Column(name="add_man", length=32)
    public String getAddMan() {
        return this.addMan;
    }
    
    public void setAddMan(String addMan) {
        this.addMan = addMan;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


