package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * MenuElement generated by hbm2java
 */
@Entity
@Table(name="tb_c_menu_element")
public class MenuElement  implements java.io.Serializable {


	 private static final long serialVersionUID = 7046017437735529386L;
	 private String elementId;
     private Menu menu;
     private String elementCode;
     private String elementName;

    public MenuElement() {
    }

	
    public MenuElement(String elementId) {
        this.elementId = elementId;
    }
    public MenuElement(String elementId, Menu menu, String elementCode, String elementName) {
       this.elementId = elementId;
       this.menu = menu;
       this.elementCode = elementCode;
       this.elementName = elementName;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="element_id", unique=true, nullable=false, length=32)
    public String getElementId() {
        return this.elementId;
    }
    
    public void setElementId(String elementId) {
        this.elementId = elementId;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_id")
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    
    @Column(name="element_code", length=32)
    public String getElementCode() {
        return this.elementCode;
    }
    
    public void setElementCode(String elementCode) {
        this.elementCode = elementCode;
    }
    
    @Column(name="element_name", length=64)
    public String getElementName() {
        return this.elementName;
    }
    
    public void setElementName(String elementName) {
        this.elementName = elementName;
    }




}


