package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * MetaData generated by hbm2java
 */
@Entity
@Table(name="tb_c_meta_data")
public class MetaData  implements java.io.Serializable {


	 private static final long serialVersionUID = -3265563558224894347L;
	 private String metaId;
     private ConfigType configType;
     private String metaName;
     private String metaCode;
     private String isAtom;
     private String description;
     private String status;
     private Integer displayOrder;

    public MetaData() {
    }

	
    public MetaData(String metaId) {
        this.metaId = metaId;
    }
    public MetaData(String metaId, ConfigType configType, String metaName, String metaCode, String isAtom, String description, String status, Integer displayOrder) {
       this.metaId = metaId;
       this.configType = configType;
       this.metaName = metaName;
       this.metaCode = metaCode;
       this.isAtom = isAtom;
       this.description = description;
       this.status = status;
       this.displayOrder = displayOrder;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="meta_id", unique=true, nullable=false, length=32)
    public String getMetaId() {
        return this.metaId;
    }
    
    public void setMetaId(String metaId) {
        this.metaId = metaId;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id")
    public ConfigType getConfigType() {
        return this.configType;
    }
    
    public void setConfigType(ConfigType configType) {
        this.configType = configType;
    }
    
    @Column(name="meta_name", length=64)
    public String getMetaName() {
        return this.metaName;
    }
    
    public void setMetaName(String metaName) {
        this.metaName = metaName;
    }
    
    @Column(name="meta_code", length=32)
    public String getMetaCode() {
        return this.metaCode;
    }
    
    public void setMetaCode(String metaCode) {
        this.metaCode = metaCode;
    }
    
    @Column(name="is_atom", length=1)
    public String getIsAtom() {
        return this.isAtom;
    }
    
    public void setIsAtom(String isAtom) {
        this.isAtom = isAtom;
    }
    
    @Column(name="description", length=512)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }




}


