package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-9-16 19:29:55 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Plug generated by hbm2java
 */
@Entity
@Table(name="tb_b_plug")
public class Plug  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String plugId;
     private String plugSortId;
     private String plugName;
     private String plugIcon;
     private String plugIconHover;
     private String plugHref;
     private String plugType;
     private Integer displayOrder;
     private String delFlag;
     private String mark1;
     private String mark2;

    public Plug() {
    }

	
    public Plug(String plugId) {
        this.plugId = plugId;
    }
    public Plug(String plugId, String plugSortId, String plugName, String plugIcon, String plugIconHover, String plugHref, String plugType, Integer displayOrder, String delFlag, String mark1, String mark2) {
       this.plugId = plugId;
       this.plugSortId = plugSortId;
       this.plugName = plugName;
       this.plugIcon = plugIcon;
       this.plugIconHover = plugIconHover;
       this.plugHref = plugHref;
       this.plugType = plugType;
       this.displayOrder = displayOrder;
       this.delFlag = delFlag;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
   	@Id
   	@GeneratedValue(generator = "generator")
    @Column(name="plug_id", unique=true, nullable=false, length=32)
    public String getPlugId() {
        return this.plugId;
    }
    
    public void setPlugId(String plugId) {
        this.plugId = plugId;
    }
    
    @Column(name="plug_sort_id", length=32)
    public String getPlugSortId() {
        return this.plugSortId;
    }
    
    public void setPlugSortId(String plugSortId) {
        this.plugSortId = plugSortId;
    }
    
    @Column(name="plug_name", length=200)
    public String getPlugName() {
        return this.plugName;
    }
    
    public void setPlugName(String plugName) {
        this.plugName = plugName;
    }
    
    @Column(name="plug_icon", length=200)
    public String getPlugIcon() {
        return this.plugIcon;
    }
    
    public void setPlugIcon(String plugIcon) {
        this.plugIcon = plugIcon;
    }
    
    @Column(name="plug_icon_hover", length=200)
    public String getPlugIconHover() {
        return this.plugIconHover;
    }
    
    public void setPlugIconHover(String plugIconHover) {
        this.plugIconHover = plugIconHover;
    }
    
    @Column(name="plug_href", length=200)
    public String getPlugHref() {
        return this.plugHref;
    }
    
    public void setPlugHref(String plugHref) {
        this.plugHref = plugHref;
    }
    
    @Column(name="plug_type", length=2)
    public String getPlugType() {
        return this.plugType;
    }
    
    public void setPlugType(String plugType) {
        this.plugType = plugType;
    }
    
    @Column(name="display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
    
    @Column(name="del_flag", length=1)
    public String getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


