package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-9-16 19:29:55 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * PlugSort generated by hbm2java
 */
@Entity
@Table(name="tb_b_plug_sort")
public class PlugSort  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String plugSortId;
     private String plugSortName;
     private Integer displayOrder;
     private String delFlag;
     private String mark1;
     private String mark2;

    public PlugSort() {
    }

	
    public PlugSort(String plugSortId) {
        this.plugSortId = plugSortId;
    }
    public PlugSort(String plugSortId, String plugSortName, Integer displayOrder, String delFlag, String mark1, String mark2) {
       this.plugSortId = plugSortId;
       this.plugSortName = plugSortName;
       this.displayOrder = displayOrder;
       this.delFlag = delFlag;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
   	@Id
   	@GeneratedValue(generator = "generator")
    @Column(name="plug_sort_id", unique=true, nullable=false, length=32)
    public String getPlugSortId() {
        return this.plugSortId;
    }
    
    public void setPlugSortId(String plugSortId) {
        this.plugSortId = plugSortId;
    }
    
    @Column(name="plug_sort_name", length=200)
    public String getPlugSortName() {
        return this.plugSortName;
    }
    
    public void setPlugSortName(String plugSortName) {
        this.plugSortName = plugSortName;
    }
    
    @Column(name="display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
    
    @Column(name="del_flag", length=1)
    public String getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


