package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Provinces generated by hbm2java
 */
@Entity
@Table(name="provinces")
public class Provinces  implements java.io.Serializable {


	 private static final long serialVersionUID = -3741618269056365141L;
	 private int id;
     private String provinceid;
     private String province;

    public Provinces() {
    }

    public Provinces(int id, String provinceid, String province) {
       this.id = id;
       this.provinceid = provinceid;
       this.province = province;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="provinceid", nullable=false, length=20)
    public String getProvinceid() {
        return this.provinceid;
    }
    
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }
    
    @Column(name="province", nullable=false, length=50)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }




}


