package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * PublicRoad generated by hbm2java
 */
@Entity
@Table(name="tb_c_public_road")
public class PublicRoad  implements java.io.Serializable {


	 private static final long serialVersionUID = 3592837393904213875L;
	 private String publicId;
     private String publicName;
     private String companyId;
     private String picture;
     private String toName;
     private String status;
     private String toRange;
     private int frequency;
     private int caps;
     private String mark1;

    public PublicRoad() {
    }

	
   
    public PublicRoad(String publicId) {
		this.publicId = publicId;
	}





	public PublicRoad(String publicId, String publicName, String companyId,
			String picture, String toName, String status,String toRange,int frequency,
			int caps, String mark1) {
		this.publicId = publicId;
		this.publicName = publicName;
		this.companyId = companyId;
		this.picture = picture;
		this.toName = toName;
		this.status = status;
		this.toRange = toRange;
		this.frequency = frequency;
		this.caps = caps;
		this.mark1 = mark1;
	}



	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="public_id", unique=true, nullable=false, length=32)
    public String getPublicId() {
        return this.publicId;
    }
	
	public void setPublicId(String publicId) {
		this.publicId = publicId;
	}

    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="mark1", length=50)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
		this.mark1 = mark1;
	}

    @Column(name="public_name", length=100)
	public String getPublicName() {
		return publicName;
	}

	public void setPublicName(String publicName) {
		this.publicName = publicName;
	}

	@Column(name="picture", length=100)
	public String getPicture() {
		return picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name="to_name", length=100)
	public String getToName() {
		return toName;
	}
	public void setToName(String toName) {
		this.toName = toName;
	}
	
	@Column(name="to_range", length=1)
	public String getToRange() {
		return toRange;
	}

	public void setToRange(String toRange) {
		this.toRange = toRange;
	}

	@Column(name="status", length=1)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name="frequency")
	public int getFrequency() {
		return frequency;
	}

	public void setFrequency(int frequency) {
		this.frequency = frequency;
	}
	
	@Column(name="caps")
	public int getCaps() {
		return caps;
	}

	public void setCaps(int caps) {
		this.caps = caps;
	}

}


