package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * PublicUser generated by hbm2java
 */
@Entity
@Table(name="tb_c_public_user")
public class PublicUser  implements java.io.Serializable {


	 private static final long serialVersionUID = 3592837393904213871L;
	 private String relateId;
     private String publicId;
     private String userCompanyId;
     private String relateType;
     private String departmentId;
     private String mark1;

    public PublicUser() {
    }



	public PublicUser(String relateId, String publicId, String userCompanyId,
			String relateType,String departmentId,String mark1) {
		this.relateId = relateId;
		this.publicId = publicId;
		this.userCompanyId = userCompanyId;
		this.relateType = relateType;
		this.departmentId = departmentId;
		this.mark1 = mark1;
	}



	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="relate_id", unique=true, nullable=false, length=32)
    public String getRelateId() {
        return this.relateId;
    }
	
	public void setRelateId(String relateId) {
		this.relateId = relateId;
	}


	 @Column(name="public_id",  length=32)
	public String getPublicId() {
		return publicId;
	}



	public void setPublicId(String publicId) {
		this.publicId = publicId;
	}


	@Column(name="user_company_id",  length=32)
	public String getUserCompanyId() {
		return userCompanyId;
	}



	public void setUserCompanyId(String userCompanyId) {
		this.userCompanyId = userCompanyId;
	}


	@Column(name="relate_type",  length=1)
	public String getRelateType() {
		return relateType;
	}



	public void setRelateType(String relateType) {
		this.relateType = relateType;
	}
	
	@Column(name="department_id",  length=32)
	public String getDepartmentId() {
		return departmentId;
	}



	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}


	@Column(name="mark1",  length=50)
	public String getMark1() {
		return mark1;
	}



	public void setMark1(String mark1) {
		this.mark1 = mark1;
	}


}


