package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-7-10 20:10:44 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * RecordGps generated by hbm2java
 */
@Entity
@Table(name="tb_c_record_gps")
public class RecordGps  implements java.io.Serializable {


     private String recordGpsId;
     private String employeeRecordId;
     private String lon;
     private String lat;
     private Date gpsDate;
     private Date addDate;
     private String mark1;
     private String mark2;

    public RecordGps() {
    }

	
    public RecordGps(String recordGpsId) {
        this.recordGpsId = recordGpsId;
    }
    public RecordGps(String recordGpsId, String employeeRecordId, String lon, String lat, Date gpsDate, Date addDate, String mark1, String mark2) {
       this.recordGpsId = recordGpsId;
       this.employeeRecordId = employeeRecordId;
       this.lon = lon;
       this.lat = lat;
       this.gpsDate = gpsDate;
       this.addDate = addDate;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="record_gps_id", unique=true, nullable=false, length=32)
    public String getRecordGpsId() {
        return this.recordGpsId;
    }
    
    public void setRecordGpsId(String recordGpsId) {
        this.recordGpsId = recordGpsId;
    }
    
    @Column(name="employee_record_id", length=32)
    public String getEmployeeRecordId() {
        return this.employeeRecordId;
    }
    
    public void setEmployeeRecordId(String employeeRecordId) {
        this.employeeRecordId = employeeRecordId;
    }
    
    @Column(name="lon", length=40)
    public String getLon() {
        return this.lon;
    }
    
    public void setLon(String lon) {
        this.lon = lon;
    }
    
    @Column(name="lat", length=40)
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gps_date", length=19)
    public Date getGpsDate() {
        return this.gpsDate;
    }
    
    public void setGpsDate(Date gpsDate) {
        this.gpsDate = gpsDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="add_date", length=19)
    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    @Column(name="mark1", length=400)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=400)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


