package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Rightconfig generated by hbm2java
 */
@Entity
@Table(name="tb_c_rightconfig")
public class Rightconfig  implements java.io.Serializable {


	 private static final long serialVersionUID = 7000247562761172616L;
	 private String rightconfigId;
     private String rightconfigName;
     private String rightconfigChecked;
     private String companyId;
     private String rightconfigType;
     private Integer level; 

    public Rightconfig() {
    }

	
    public Rightconfig(String rightconfigId) {
        this.rightconfigId = rightconfigId;
    }
    public Rightconfig(String rightconfigId, String rightconfigName, String rightconfigChecked, String companyId, String rightconfigType, Integer level) {
       this.rightconfigId = rightconfigId;
       this.rightconfigName = rightconfigName;
       this.rightconfigChecked = rightconfigChecked;
       this.companyId = companyId;
       this.setRightconfigType(rightconfigType);
       this.setLevel(level);
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="rightconfig_id", unique=true, nullable=false, length=32)
    public String getRightconfigId() {
        return this.rightconfigId;
    }
    
    public void setRightconfigId(String rightconfigId) {
        this.rightconfigId = rightconfigId;
    }
    
    @Column(name="rightconfig_name", length=40)
    public String getRightconfigName() {
        return this.rightconfigName;
    }
    
    public void setRightconfigName(String rightconfigName) {
        this.rightconfigName = rightconfigName;
    }
    
    @Column(name="rightconfig_checked", length=1)
    public String getRightconfigChecked() {
        return this.rightconfigChecked;
    }
    
    public void setRightconfigChecked(String rightconfigChecked) {
        this.rightconfigChecked = rightconfigChecked;
    }
    
    @Column(name="company_id", length=32)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    @Column(name="rightconfig_type", length=2)
	public String getRightconfigType() {
		return rightconfigType;
	}


	public void setRightconfigType(String rightconfigType) {
		this.rightconfigType = rightconfigType;
	}

	@Column(name="level", length=2)
	public Integer getLevel() {
		return level;
	}


	public void setLevel(Integer level) {
		this.level = level;
	}




}


