package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * RoleMenu generated by hbm2java
 */
@Entity
@Table(name="tb_c_role_menu")
public class RoleMenu  implements java.io.Serializable {


	 private static final long serialVersionUID = -8526982437945179693L;
	 private String id;
     private Role role;
     private String menuId;

    public RoleMenu() {
    }

	
    public RoleMenu(String id) {
        this.id = id;
    }
    public RoleMenu(String id, Role role, String menuId) {
       this.id = id;
       this.role = role;
       this.menuId = menuId;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id")
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    
    @Column(name="menu_id", length=32)
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }




}


