package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * StatisticsConfig generated by hbm2java
 */
@Entity
@Table(name="tb_c_statistics_config")
public class StatisticsConfig  implements java.io.Serializable {


 	 private static final long serialVersionUID = 7253492933717132241L;
	 private String id;
     private String menuId;
     private String menuName;
     private String path;
     private String moduleName;

    public StatisticsConfig() {
    }

	
    public StatisticsConfig(String id) {
        this.id = id;
    }
    public StatisticsConfig(String id, String menuId, String menuName, String path, String moduleName) {
       this.id = id;
       this.menuId = menuId;
       this.menuName = menuName;
       this.path = path;
       this.moduleName = moduleName;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="id", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="menu_id", length=32)
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    
    @Column(name="menu_name", length=64)
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    
    @Column(name="path", length=256)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    
    @Column(name="module_name", length=64)
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }




}


