package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-3-6 9:37:06 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name="tb_c_token")
public class Token  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID. <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = -8458780464958927647L;
	 private String tokenId;
     private String employeeId;
     private String tokenValue;
     private String passSalt;
     private Date tokenDate;
     private Date addDate;
     private String mark1;
     private String mark2;

    public Token() {
    }

	
    public Token(String tokenId) {
        this.tokenId = tokenId;
    }
    public Token(String tokenId, String employeeId, String tokenValue, String passSalt, Date tokenDate, Date addDate, String mark1, String mark2) {
       this.tokenId = tokenId;
       this.employeeId = employeeId;
       this.tokenValue = tokenValue;
       this.passSalt = passSalt;
       this.tokenDate = tokenDate;
       this.addDate = addDate;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="token_id", unique=true, nullable=false, length=32)
    public String getTokenId() {
        return this.tokenId;
    }
    
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="token_value", length=32)
    public String getTokenValue() {
        return this.tokenValue;
    }
    
    public void setTokenValue(String tokenValue) {
        this.tokenValue = tokenValue;
    }
    
    @Column(name="pass_salt", length=64)
    public String getPassSalt() {
        return this.passSalt;
    }
    
    public void setPassSalt(String passSalt) {
        this.passSalt = passSalt;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="token_date", length=19)
    public Date getTokenDate() {
        return this.tokenDate;
    }
    
    public void setTokenDate(Date tokenDate) {
        this.tokenDate = tokenDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="add_date", length=19)
    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


