package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-22 21:25:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * UserMaster generated by hbm2java
 */
@Entity
@Table(name="tb_b_user_master")
public class UserMaster  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = -4567910939567792375L;
	 private String employeeMasterId;
     private Master master;
     private String employeeId;
     private String mark1;
     private String mark2;

    public UserMaster() {
    }

	
    public UserMaster(String employeeMasterId) {
        this.employeeMasterId = employeeMasterId;
    }
    public UserMaster(String employeeMasterId, Master master, String employeeId, String mark1, String mark2) {
       this.employeeMasterId = employeeMasterId;
       this.master = master;
       this.employeeId = employeeId;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="employee_master_id", unique=true, nullable=false, length=32)
    public String getEmployeeMasterId() {
        return this.employeeMasterId;
    }
    
    public void setEmployeeMasterId(String employeeMasterId) {
        this.employeeMasterId = employeeMasterId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="master_id")
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    
    @Column(name="employee_id", length=32)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


