package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-24 16:42:28 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserCompanyChanged generated by hbm2java
 */
@Entity
@Table(name="tb_c_user_company_changed")
public class UserCompanyChanged  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = -2498524917154966427L;
	 private UserCompanyChangedId id;
     private String updateType;
     private String mark1;
     private String mark2;

    public UserCompanyChanged() {
    }

	
    public UserCompanyChanged(UserCompanyChangedId id) {
        this.id = id;
    }
    public UserCompanyChanged(UserCompanyChangedId id, String updateType, String mark1, String mark2) {
       this.id = id;
       this.updateType = updateType;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
    @AttributeOverride(name="userCompanyId", column=@Column(name="user_company_id", nullable=false, length=32) ), 
    @AttributeOverride(name="groupVersionNum", column=@Column(name="group_version_num", nullable=false) ) } )
    public UserCompanyChangedId getId() {
        return this.id;
    }
    
    public void setId(UserCompanyChangedId id) {
        this.id = id;
    }
    
    @Column(name="update_type", length=2)
    public String getUpdateType() {
        return this.updateType;
    }
    
    public void setUpdateType(String updateType) {
        this.updateType = updateType;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


