package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-5-29 10:13:00 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * UserModify generated by hbm2java
 */
@Entity
@Table(name="tb_c_user_modify")
public class UserModify  implements java.io.Serializable {


     /**
	 * 属性名称：serialVersionUID <br/>
	 * 类型：long
	 */
	 private static final long serialVersionUID = 3735840823118336680L;
	 private String userModifyId;
     private String userCompanyId;
     private String employeeName;
     private String userCompany;
     private String departmentName;
     private String headshipName;
     private String mobile;
     private String homeTelephone;
     private String weibo;
     private String weixin;
     private String school;
     private String userMajor;
     private String userGrade;
     private String userClass;
     private String studentId;
     private Date birthday;
     private String nativePlace;
     private String address;
     private String homeAddress;
     private String remark;
     private String manageFlag;
     private String mobileShort;
     private String telShort;
     private String telephone;
     private String email;
     private String qq;
     private String picture;
     private String mood;
     private String isAudited;
     private String mark1;
     private String mark2;

    public UserModify() {
    }

	
    public UserModify(String userModifyId) {
        this.userModifyId = userModifyId;
    }
    public UserModify(String userModifyId, String userCompanyId, String employeeName, String userCompany, String departmentName, String headshipName, String mobile, String homeTelephone, String weibo, String weixin, String school, String userMajor, String userGrade, String userClass, String studentId, Date birthday, String nativePlace, String address, String homeAddress, String remark, String manageFlag, String mobileShort, String telShort, String telephone, String email, String qq, String picture, String mood, String isAudited, String mark1, String mark2) {
       this.userModifyId = userModifyId;
       this.userCompanyId = userCompanyId;
       this.employeeName = employeeName;
       this.userCompany = userCompany;
       this.departmentName = departmentName;
       this.headshipName = headshipName;
       this.mobile = mobile;
       this.homeTelephone = homeTelephone;
       this.weibo = weibo;
       this.weixin = weixin;
       this.school = school;
       this.userMajor = userMajor;
       this.userGrade = userGrade;
       this.userClass = userClass;
       this.studentId = studentId;
       this.birthday = birthday;
       this.nativePlace = nativePlace;
       this.address = address;
       this.homeAddress = homeAddress;
       this.remark = remark;
       this.manageFlag = manageFlag;
       this.mobileShort = mobileShort;
       this.telShort = telShort;
       this.telephone = telephone;
       this.email = email;
       this.qq = qq;
       this.picture = picture;
       this.mood = mood;
       this.isAudited = isAudited;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="user_modify_id", unique=true, nullable=false, length=32)
    public String getUserModifyId() {
        return this.userModifyId;
    }
    
    public void setUserModifyId(String userModifyId) {
        this.userModifyId = userModifyId;
    }
    
    @Column(name="user_company_id", length=32)
    public String getUserCompanyId() {
        return this.userCompanyId;
    }
    
    public void setUserCompanyId(String userCompanyId) {
        this.userCompanyId = userCompanyId;
    }
    
    @Column(name="employee_name", length=40)
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
    
    @Column(name="user_company", length=200)
    public String getUserCompany() {
        return this.userCompany;
    }
    
    public void setUserCompany(String userCompany) {
        this.userCompany = userCompany;
    }
    
    @Column(name="department_name", length=80)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    
    @Column(name="headship_name", length=80)
    public String getHeadshipName() {
        return this.headshipName;
    }
    
    public void setHeadshipName(String headshipName) {
        this.headshipName = headshipName;
    }
    
    @Column(name="mobile", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="home_telephone", length=20)
    public String getHomeTelephone() {
        return this.homeTelephone;
    }
    
    public void setHomeTelephone(String homeTelephone) {
        this.homeTelephone = homeTelephone;
    }
    
    @Column(name="weibo", length=80)
    public String getWeibo() {
        return this.weibo;
    }
    
    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }
    
    @Column(name="weixin", length=80)
    public String getWeixin() {
        return this.weixin;
    }
    
    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }
    
    @Column(name="school", length=200)
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    
    @Column(name="user_major", length=80)
    public String getUserMajor() {
        return this.userMajor;
    }
    
    public void setUserMajor(String userMajor) {
        this.userMajor = userMajor;
    }
    
    @Column(name="user_grade", length=80)
    public String getUserGrade() {
        return this.userGrade;
    }
    
    public void setUserGrade(String userGrade) {
        this.userGrade = userGrade;
    }
    
    @Column(name="user_class", length=80)
    public String getUserClass() {
        return this.userClass;
    }
    
    public void setUserClass(String userClass) {
        this.userClass = userClass;
    }
    
    @Column(name="student_id", length=80)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="birthday", length=19)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    
    @Column(name="native_place", length=64)
    public String getNativePlace() {
        return this.nativePlace;
    }
    
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }
    
    @Column(name="address", length=400)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="home_address", length=80)
    public String getHomeAddress() {
        return this.homeAddress;
    }
    
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }
    
    @Column(name="remark", length=400)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="manage_flag", length=2)
    public String getManageFlag() {
        return this.manageFlag;
    }
    
    public void setManageFlag(String manageFlag) {
        this.manageFlag = manageFlag;
    }
    
    @Column(name="mobile_short", length=20)
    public String getMobileShort() {
        return this.mobileShort;
    }
    
    public void setMobileShort(String mobileShort) {
        this.mobileShort = mobileShort;
    }
    
    @Column(name="tel_short", length=20)
    public String getTelShort() {
        return this.telShort;
    }
    
    public void setTelShort(String telShort) {
        this.telShort = telShort;
    }
    
    @Column(name="telephone", length=20)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    @Column(name="email", length=32)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="qq", length=18)
    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }
    
    @Column(name="picture", length=80)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    
    @Column(name="mood", length=800)
    public String getMood() {
        return this.mood;
    }
    
    public void setMood(String mood) {
        this.mood = mood;
    }
    
    @Column(name="is_audited", length=1)
    public String getIsAudited() {
        return this.isAudited;
    }
    
    public void setIsAudited(String isAudited) {
        this.isAudited = isAudited;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }




}


