package com.cmcc.zysoft.sellmanager.model;
// Generated 2013-6-25 19:31:31 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * UserDepartment generated by hbm2java
 */
@Entity
@Table(name="tb_c_user_department")
public class UserDepartment  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userDepartmentId;
     private String userCompanyId;
     private String headshipId;
     private String headshipName;
     private String departmentId;
     private String departmentPath;
     private Integer taxis;
     private String visibleFlag;
     private String mark1;
     private String mark2;

    public UserDepartment() {
    }

	
    public UserDepartment(String userDepartmentId) {
        this.userDepartmentId = userDepartmentId;
    }
    public UserDepartment(String userDepartmentId, String userCompanyId, String headshipId, String departmentId, String departmentPath, Integer taxis, String visibleFlag, String mark1, String mark2) {
       this.userDepartmentId = userDepartmentId;
       this.userCompanyId = userCompanyId;
       this.headshipId = headshipId;
       this.departmentId = departmentId;
       this.departmentPath = departmentPath;
       this.taxis = taxis;
       this.visibleFlag = visibleFlag;
       this.mark1 = mark1;
       this.mark2 = mark2;
    }
   
    @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="user_department_id", unique=true, nullable=false, length=32)
    public String getUserDepartmentId() {
        return this.userDepartmentId;
    }
    
    public void setUserDepartmentId(String userDepartmentId) {
        this.userDepartmentId = userDepartmentId;
    }
    
    @Column(name="user_company_id", length=32)
    public String getUserCompanyId() {
        return this.userCompanyId;
    }
    
    public void setUserCompanyId(String userCompanyId) {
        this.userCompanyId = userCompanyId;
    }
    
    @Column(name="headship_id", length=32)
    public String getHeadshipId() {
        return this.headshipId;
    }
    
    public void setHeadshipId(String headshipId) {
        this.headshipId = headshipId;
    }
    
    @Column(name="department_id", length=32)
    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    
    @Column(name="department_path", length=800)
    public String getDepartmentPath() {
        return this.departmentPath;
    }
    
    public void setDepartmentPath(String departmentPath) {
        this.departmentPath = departmentPath;
    }
    
    @Column(name="taxis")
    public Integer getTaxis() {
        return this.taxis;
    }
    
    public void setTaxis(Integer taxis) {
        this.taxis = taxis;
    }
    
    @Column(name="visible_flag", length=1)
    public String getVisibleFlag() {
        return this.visibleFlag;
    }
    
    public void setVisibleFlag(String visibleFlag) {
        this.visibleFlag = visibleFlag;
    }
    
    @Column(name="mark1", length=200)
    public String getMark1() {
        return this.mark1;
    }
    
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }
    
    @Column(name="mark2", length=200)
    public String getMark2() {
        return this.mark2;
    }
    
    public void setMark2(String mark2) {
        this.mark2 = mark2;
    }

    @Column(name="headship_name",length=200)
	public String getHeadshipName() {
		return headshipName;
	}


	public void setHeadshipName(String headshipName) {
		this.headshipName = headshipName;
	}




}


